### ISSUE TITLE
无法使用translator/dictionary的方式加入多个词典, 求助.

### ISSUE THREAD

**Issue by rsyqvthv** [hosxy/rime-aurora-pinyin#10]
aurora是我唯一的输入方法, 用translator/dictionary的方式挂载了一些字典, 但发现这些挂载字典中的词并未加载.  加入了新的字典后进行"重新部署"也是一闪而过, 而不是原先有个时间漏斗, 需要等上一阵那样.

我的输入法选择, aurora极光是我唯一的选择.

<img width="356" alt="【小狼毫】方案選單設定_20211005_201353" src="https://user-images.githubusercontent.com/2230369/136088030-54eecf89-949f-4d1d-8587-308f7674479a.png">

这是我的文件目录, 和aurora相关的就这4个:

<img width="164" alt="rime_20211005_201504" src="https://user-images.githubusercontent.com/2230369/136088174-b0f47214-5725-4abe-9487-ef518796d76f.png">

aurora_pinyin.custom.yaml 的内容:

```yaml
patch:
  'translator/dictionary': aurora_pinyin.extended
```

aurora_pinyin.extended.dict.yaml的内容:

```yaml
# encoding: utf-8

---
name: aurora_pinyin.extended
version: "2021/09/22"
sort: by_weight
use_preset_vocabulary: true
import_tables:
  - aurora_pinyin
  - english
  - chinese_ancient
  - chinese_address
  - chinese_chengyu
  - chinese_names
  - chinese_proberb
...
# 自定义的词条
^_^	hh	5
T_T	kk	5
```

至此, `aurora_pinyin.extended.dict.yaml` 文件似乎是被读取了的, 因为我自定义的两个词条是可以输入的.

但是通过import_tabes方式引入的词条则似乎只有`english`被完全引入了, 而其他的似乎只引用了部分. 
我尝试输入一些字典里面的词语, 都是有的有, 有的没有. 这让我很困惑. 

<img width="165" alt="rime_20211005_202026" src="https://user-images.githubusercontent.com/2230369/136088905-0ae79f38-2eba-4bff-ad24-aac44bd96bd3.png">

我已经逐个检查过字典, 似乎都符合规范: 

- 所有的字典都是utf-8编码, 我也尝试过使用utf-8 bom, 没有改变. 
- 所有字典开头都会写 `# encoding: utf-8`
- 所有字典开始`---`后的name中, 都会写 `name: 文件名`, 文件名不包括.dict.yaml部分.

无论怎么设置, 只要重新部署都是一闪而过. 当然改变也不会被应用.

我甚至在task manager中关闭了weaselserver.exe, 然后再重新启动该服务, 仍然无济于事.
