### ISSUE TITLE
可以配合 rime-easy-en 配置中英混合输入吗？

### ISSUE THREAD

**Issue by everyx** [hosxy/rime-aurora-pinyin#14]
我的 aurora_pinyin.custom.yaml 如下，不知道为什么不行

```yaml
patch:
  # 启用语句流输入，空格选词，按回车或者标点符号才上屏。
  engine/processors/@last: fluency_editor

  # 加载词库
  translator/dictionary: aurora_pinyin.extended

  # 启用表情报输入，依赖 [rime-emoji](https://github.com/rime/rime-emoji)
  # 使用自定义 path 防止 emoji 字符被 filter 掉。
  __include: emoji_suggestion.patch:/patch

  __include: easy_en:/patch
  # easy_en/initial_quality: 0.5
  # easy_en/use_wordninja_rs: true


  # 自定义的 lua 插件
  engine/translators/@next: lua_translator@date_translator

  # 关掉反查。
  # recognizer/patterns/reverse_lookup:

```
