### ISSUE TITLE
如何让`键(输入一个撇)直接输入, 而不会出现选单?

### ISSUE THREAD

**Issue by rsyqvthv** [hosxy/rime-aurora-pinyin#9]
`键是非常常用的一个按键, 尤其我经常使用markdown.

但是使用了aurora后, 按下`会出现菜单, 需要选择后才行. 

不知道怎么才能取消他, 让我可以直接输入这个按键? 

感谢.

**Comment by flyingicedragon** [comment]
修改 symbols.yaml 文件。找到对应行修改。

```
'`' : [ commit: '`' ]
```

**Comment by rsyqvthv** [comment]
@flyingicedragon 

感谢你的回覆, 但似乎不起作用. 

我先按照你的方法, 直接修改了`Rime\weasel-0.14.3\data`中的symbols.yaml, 将其中全角和半角的

<img width="320" alt="20210924_081151" src="https://user-images.githubusercontent.com/2230369/134633450-2a8013eb-4107-42cb-b377-665dc4c09127.png">

重新部署后是这样:

<img width="138" alt="MouseInc 081405" src="https://user-images.githubusercontent.com/2230369/134633638-c91dab6b-12f4-4b61-acad-0e62833d307e.png">

不知道哪里出了问题?

**Comment by rsyqvthv** [comment]
我在`aurora_pinyin.schema.yaml`中找到了一个可能相关的设置: 

```yaml
recognizer:
  import_preset: default
  patterns:
    punct: '^/([0-9]0?|[A-Za-z]+)$'
    reverse_lookup: "`[a-z]*'?$"
```

如果注释掉`reverse_lookup: "`[a-z]*'?$"`这句, 即便不更改`symbol.yaml`, 输入也是正常的.

请问, 这个`reverse_lookup`是做什么用的呢?

感谢.
